### ISSUE TITLE
UnboundLocalError: local variable 'api' referenced before assignment.

### ISSUE THREAD

**Issue by mrkaraly** [omergunal/PoT#1]
The issue is in the title :octocat:

**Comment by omergunal** [comment]
i guess you didn't update api keys on PoT.py. You can get api keys from this link: https://apps.twitter.com/

**Comment by mrkaraly** [comment]
Thanks :D

2018-02-23 11:15 GMT+03:00 Ömer Günal <notifications@github.com>:
