### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by Anonyvius** [omergunal/PoT#7]
Just installed everything and configured the `cfg`. Now i wanted to start the process using: `python PoT.py -u [Username]` and now i´m gettin this:

> Traceback (most recent call last):
  File "PoT.py", line 8, in <module>
    from fake import Fake
  File "/root/PoT/fake.py", line 5, in <module>
    import urllib.request
ImportError: No module named request
root@Anonyvius:~/PoT# 

any idea how to fix?

**Comment by omergunal** [comment]
I forgot to add "request" on requirements.txt . You should run this command: `sudo pip install requests` or this `sudo pip3 install requests`

**Comment by Anonyvius** [comment]
Yeah, that's what i also thought. So i already did, but the error is still there.

**Comment by omergunal** [comment]
are you sure trying these with python3?

**Comment by Anonyvius** [comment]
kinda, tried python3:

> root@Anonyvius:~/PoT# python3 PoT.py 
[-] name 'print_help' is not defined
root@Anonyvius:~/PoT# 

but because i got this error i tought it would be only python

**Comment by omergunal** [comment]
I changed source code, can  you download and try again?
