### ISSUE TITLE
Not finding the tweepy 

### ISSUE THREAD

**Issue by Mo95ze** [omergunal/PoT#9]
Hi sir, 
I get an issue in using the PoT tool, I installed all of the requirements to run it correctly but unfortunately one I run it show for me:
  Traceback (most recent call last):
  File "PoT.py", line 4, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'

I tried to solve the issue by re-install the tweepy by using the pip but at the end the same error keep repeating and until now I have not solve it.

**Comment by omergunal** [comment]
are you sure install tweepy on **python3**? 
`pip3 install tweepy`

**Comment by Mo95ze** [comment]
sir, when I run pip3 install tweepy in command line it shows for me the following: 

Requirement already satisfied: tweepy in /usr/local/lib/python2.7/dist-packages/tweepy-3.6.0-py2.7.egg (3.6.0)
Requirement already satisfied: PySocks>=1.5.7 in /usr/lib/python2.7/dist-packages (from tweepy) (1.6.5)
Requirement already satisfied: requests>=2.11.1 in /usr/lib/python2.7/dist-packages (from tweepy) (2.18.4)
Requirement already satisfied: requests_oauthlib>=0.7.0 in /usr/local/lib/python2.7/dist-packages (from tweepy) (1.0.0)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python2.7/dist-packages (from tweepy) (1.11.0)
Requirement already satisfied: oauthlib>=0.6.2 in /usr/local/lib/python2.7/dist-packages (from requests_oauthlib>=0.7.0->tweepy) (2.1.0)

I do not know if it is installing in python2.7 or it is be in python3

**Comment by omergunal** [comment]
Can you run these commands? :
`sudo pip uninstall tweepy`
`sudo pip3 install tweepy`
I think it will be ok

**Comment by Mo95ze** [comment]
I tried to do like this previously but still the issue of not finding the tweepy and I tried it right know but same thing occurring of not finding the tweepy.

**Comment by omergunal** [comment]
You can not install on python3 because tweepy  installed on python2. firstly, you should remove it and install on python3.
Can you try this:
![selection_138](https://user-images.githubusercontent.com/19760132/42456815-7c122ec8-839e-11e8-9e58-cbee9ce65804.png)
Let's see if you can get an error

**Comment by Mo95ze** [comment]
I did like you do and I did not get any error but I will try it with PoT to see if it is ok or not!!!!

**Comment by Mo95ze** [comment]
I run it with a username and the same issue is occurring:


python3 PoT.py -u 
Traceback (most recent call last):
  File "PoT.py", line 4, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'

**Comment by omergunal** [comment]
Hmm ok, try this one please
`sudo pip3 install virtualenv`

**Comment by omergunal** [comment]
Or this one, after uninstall the tweepy:
`pip3 install --user tweepy`

**Comment by Mo95ze** [comment]
I did what you said but unfortunately same issue occurring. I think issue in installing tweepy in python2.7. once I install tweepy it is directly stored in python2.7 lib, I do not know how to make it going to python3!!!!!

**Comment by omergunal** [comment]
maybe you can install from source code
```
git clone https://github.com/tweepy/tweepy.git
cd tweepy
python3 setup.py install
```

**Comment by Mo95ze** [comment]
Thank you sir for your helping, it is working right now.

Thanks

**Comment by omergunal** [comment]
i glad to hear that :)
I am closing this issue.
